### ISSUE TITLE
How to zoom with Aperture without a computer touchscreen? As it requires two fingers.

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/scrcpy#1]
[LineageOS/android_packages_apps_Aperture](https://github.com/LineageOS/android_packages_apps_Aperture)

 - [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Benjamin-Loison** [comment]
[scrcpy/blob/21e2e2606e683326d9171afb106a5473f16d8bb9/doc/video.md](https://github.com/Genymobile/scrcpy/blob/21e2e2606e683326d9171afb106a5473f16d8bb9/doc/video.md) does not mention *zoom*.

**Comment by Benjamin-Loison** [comment]
If already using Aperture to zoom or focus, then:

```bash
scrcpy --video-source=camera
```
<details>
<summary>Output:</summary>

```
scrcpy 3.2 <https://github.com/Genymobile/scrcpy>
INFO: Camera video source: control disabled
INFO: Camera video source: microphone audio source selected
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.1.31:38205              device  FP4
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 205.1 MB/s (90888 bytes in 0.000s)
[server] INFO: Device: [Fairphone] Fairphone FP4 (Android 15)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.2.8-1ubuntu1~24.04.1
INFO: Trilinear filtering enabled
[server] INFO: Using camera '0'
[server] ERROR: Video encoding error
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error
java.io.IOException: android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4): connectHelper:2537: Higher-priority client using camera, ID "0" currently unavailable
	at com.genymobile.scrcpy.video.CameraCapture.init(CameraCapture.java:111)
	at com.genymobile.scrcpy.video.SurfaceCapture.init(SurfaceCapture.java:33)
	at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:70)
	at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:296)
	at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1119)
Caused by: android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4): connectHelper:2537: Higher-priority client using camera, ID "0" currently unavailable
	at android.hardware.camera2.utils.ExceptionUtils.throwAsPublicException(ExceptionUtils.java:75)
	at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:1157)
	at android.hardware.camera2.CameraManager.openCameraImpl(CameraManager.java:1508)
	at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:1266)
	at com.genymobile.scrcpy.video.CameraCapture.openCamera(CameraCapture.java:311)
	at com.genymobile.scrcpy.video.CameraCapture.init(CameraCapture.java:109)
	... 5 more
Caused by: android.os.ServiceSpecificException: connectHelper:2537: Higher-priority client using camera, ID "0" currently unavailable (code 7)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3275)
	at android.os.Parcel.createException(Parcel.java:3245)
	at android.os.Parcel.readException(Parcel.java:3228)
	at android.os.Parcel.readException(Parcel.java:3170)
	at android.hardware.ICameraService$Stub$Proxy.connectDevice(ICameraService.java:1035)
	at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:1132)
	... 9 more
```
</details>

**Comment by Benjamin-Loison** [comment]
Related to [Benjamin-Loison/android_packages_apps_Aperture/issues/41](https://github.com/Benjamin-Loison/android_packages_apps_Aperture/issues/41).

**Comment by Benjamin-Loison** [comment]
DuckDuckGo and Google search *scrcpy zoom*.

[Genymobile/scrcpy/issues/24#issuecomment-671063070](https://github.com/Genymobile/scrcpy/issues/24#issuecomment-671063070) works as wanted thanks to <kbd>ctrl</kbd> and moving left click hold.
